const User = require("../models/UserModel")
const Admin = require("../models/AdminModel")
const GymMember = require("../models/GymMemberModel")
const GymTrainer = require("../models/GymTrainerModel")
const Membership = require("../models/MembershipModel")
const MemberSchedule = require("../models/MemberScheduleModel")
const Diet = require("../models/DietModel")
const Products = require("../models/ProductModel")
const Orders = require("../models/OrdersModel")
const ShippingDetails = require("../models/ShippingDetailsModel")
const Payment = require("../models/PaymentModel")
const Notice = require("../models/NoticeModel")
const FeatureProducts = require("../models/FeaturedProducts")

User.hasOne(Admin)
User.hasOne(GymMember)
User.hasOne(GymTrainer)
Membership.hasOne(GymMember)
MemberSchedule.hasOne(GymMember)
Diet.hasOne(GymMember)
Products.hasOne(Orders)
User.hasOne(Orders)
ShippingDetails.hasOne(Orders)
User.hasOne(ShippingDetails)
User.hasOne(Payment)
Orders.hasOne(Payment)
Admin.hasOne(Notice)
Products.hasOne(FeatureProducts)